### ISSUE TITLE
Questions about mot bbox size

### ISSUE THREAD

**Issue by shentaowang** [VisDrone/VisDrone-Dataset#7]
I found that the size of the bbox given in the mot dataset is much larger than the size of the actual object, is this normal? The bbox looks like this

![image](https://user-images.githubusercontent.com/14112786/82280439-77733c00-99c1-11ea-8241-b3b04e41af29.png)

Thank you very much if you can make some suggestions！

**Comment by basakakyuz** [comment]
Hi, did you find out why this happens?
